# syntax = docker/dockerfile:experimental
FROM python:3.8-buster
RUN apt update \
    && apt install -y git
RUN git clone https://github.com/PederHA/vjemmieapi.git
WORKDIR /vjemmieapi
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

CMD ["uvicorn", "vjemmieapi:app"]