# syntax = docker/dockerfile:experimental
FROM python:3.8-buster
WORKDIR /app
RUN apt update \
    && apt install -y ffmpeg libopus0 tesseract-ocr webhook
COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

CMD ["python", "run.py", "test"]